/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package fizzbuzz;

// call a method with the signature "String exec(int number)" in the class FizzBuzz
// if 'number' is divisible by 3 return "Fizz"
// if 'number' is divisible by 5 return "Buzz"  
// if 'number' is divisible by 3 and by 5 return "FizzBuzz"
// otherwise, return the string representation of 'number'  

public class FizzBuzz {
    public boolean someLibraryMethod() {
        return true;
    }
}
