/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package fizzbuzz;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class FizzBuzzTest {
    @Test void testSomeLibraryMethod() {
        FizzBuzz fb = new FizzBuzz();
        assertTrue(fb.someLibraryMethod(), "someLibraryMethod should return 'true'");
    }
}
