/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package fizzbuzz;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

//  Rules of TDD: (Transforms that change behavior w/o changing structure)
//  1.  You are not allowed to write production code unless it 
//      is to make a failing test pass
//  2.  You are not allowed to write any more of a unit test 
//      than is sufficient to fail...compile errors count as failing.
//  3.  You are not allowed to write any more code than 
//      required to make the test pass

//  Rules of refactoring (Refactors change structure w/o changing behavior)
//  1.  You are not allowed to refactor unless all of your tests are green (or disabled/skipped)
//  2.  You are not allowed to change any behavior
//  3.  Run your tests on EVERY code change


//  tips
//  use well-named tests
//  don't write unnecessary tests
//  make the smallest possible changes
//  follow THINK, RED, GREEN, REFACTOR
//  run your tests every time you touch your code

class FizzBuzzTest {
    @Test void testSomeLibraryMethod() {
        FizzBuzz fb = new FizzBuzz();
        assertTrue(fb.someLibraryMethod(), "someLibraryMethod should return 'true'");
    }
}
