/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package stringCalc;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class StringCalcTest {
    @Test void testSomeLibraryMethod() {
        StringCalc calc = new StringCalc();
        assertEquals(0,calc.Add(""));
    }
}
