/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package bowling;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class GameTest {
    @Test void testSomeLibraryMethod() {
        Game game = new Game();
        assertTrue(game.someLibraryMethod(), "someLibraryMethod should return 'true'");
    }
}
